language: java

jdk:
  - oraclejdk8

os: linux
dist: trusty

services:
 - docker

addons:
  chrome: stable

before_install:
 - docker network create grid
 - docker pull selenium/hub
 - docker run -d -p 4444:4444 --net grid  --name sh selenium/hub
 - docker pull selenium/node-chrome
 - docker run -d --net grid -e HUB_HOST=sh -v /dev/shm:/dev/shm --name chrome selenium/chrome-node


script: bash code_run.sh

After_script:
docker network rm grid


