language: java

jdk:
  - oraclejdk8

os: linux
dist: trusty


addons:
  chrome: stable

services:
 - docker


env:
  global:
    - TEST_SLEEPS="0.7"
    - ADDED_TEST_SLEEP="6.5"
    - DOCKER_VERSION="stable"
 
before_install: bash docker_bash.sh

script: bash code_run.sh






