language: java

jdk:
  - oraclejdk8

os: linux
dist: trusty

services:
 - docker

addons:
  chrome: stable

before_script: bash docker_bash.sh

script: bash code_run.sh


after_script:
 -docker sh logs
